# -*- coding: utf-8 -*-
"""recommendations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKpBVVRPCNmTeYkSl9BRpUkV_yRoDfGR
"""

def get_latest_5_quizzes():
    pass

def calculate_topic_performance():
    pass

def detect_weakest_topics():
    pass

def determine_difficulty():
    pass

def generate_recommendations():
    pass